/human:
  - 0.0
  - 0.0
  - 0.3
/bin:
  - 0.0
  - 0.0
  - 0.15
/rosie0:
  - 0.0
  - 0.0
  - 0.275
/rosie1:
  - 0.0
  - 0.0
  - 0.275
/rosie2: 
  - 0.0
  - 0.0
  - 0.275
/turtlebot1:
  - 0.0
  - 0.0
  - 0.1
/turtlebot2:
  - 0.0
  - 0.0
  - 0.1
/turtlebot3:
  - 0.0
  - 0.0
  - 0.1
/turtlebot4:
  - 0.0
  - 0.0
  - 0.1
/turtlebot5:
  - 0.0
  - 0.0
  - 0.1
/turtlebot6:
  - 0.0
  - 0.0
  - 0.1
/turtlebot7:
  - 0.0
  - 0.0
  - 0.1
obstacle1:
  - -2.12
  - 1.97
  - 0.1
obstacle2:
  - -0.32
  - 1.98
  - 0.1
obstacle3:
  - -0.3
  - -0.3
  - 0.1
obstacle4:
  - -2.03
  - -0.32
  - 0.1