/human:
  - 0.0
  - 0.0
  - 0.3
/rosie0:
  - 0.0
  - 0.0
  - 0.275
/rosie1:
  - 0.0
  - 0.0
  - 0.275
/rosie2: 
  - 0.0
  - 0.0
  - 0.275
/turtlebot1:
  - 0.0
  - 0.0
  - 0.1
/turtlebot2:
  - 0.0
  - 0.0
  - 0.1
/turtlebot3:
  - 0.0
  - 0.0
  - 0.1
/turtlebot4:
  - 0.0
  - 0.0
  - 0.1
/turtlebot5:
  - 0.0
  - 0.0
  - 0.1
/turtlebot6:
  - 0.0
  - 0.0
  - 0.1
/turtlebot7:
  - 0.0
  - 0.0
  - 0.1
obstacle1:
  - -2.132
  - -0.853
  - 0.1
obstacle2:
  - 1.608
  - -0.820
  - 0.1
obstacle3:
  - 1.610
  - -2.632
  - 0.1
obstacle4:
  - 1.852
  - 2.660
  - 0.1