a2:
  dependency: {}
  guard: r2
  label: p42
  type: assisting
  weight: 30
c13:
  dependency:
    h1:
    - r1
    - r3
    h2:
    - r2
  guard: r1 || r3
  label: p41
  type: collaborative
  weight: 10
l123:
  dependency: {}
  guard: '1'
  label: d41
  type: local
  weight: 20
