action:
  actions:
    a2:
      dependency: {}
      guard: r2
      label: a2
      type: assisting
      weight: 30
    c13:
      dependency:
        h1:
        - r1
        - r3
        h2:
        - r2
      guard: r1 || r3
      label: c13
      type: collaborative
      weight: 10
    free:
      dependency: {}
      guard: '1'
      label: ''
      type: local
      weight: 1
    l123:
      dependency: {}
      guard: '1'
      label: l123
      type: local
      weight: 20
  initial: free
  type: ActionModel
motion:
  initial: r1
  regions:
    r1:
      label: r1
      pose:
      - 15
      - 45
      - 3
      weights:
      - 0
      - 2
      - 5
    r2:
      label: r2
      pose:
      - 0
      - 20
      - 3
      weights:
      - 4
      - 0
      - 7
    r3:
      label: r3
      pose:
      - 15
      - 10
      - 3
      weights:
      - 2
      - 3
      - 0
  type: MotionTS
