r1:
  label: r1
  pose:
  - 15
  - 45
  - 3
  weights:
  - 0
  - 2
  - 5
r2:
  label: r2
  pose:
  - 0
  - 20
  - 3
  weights:
  - 4
  - 0
  - 7
r3:
  label: r3
  pose:
  - 15
  - 10
  - 3
  weights:
  - 2
  - 3
  - 0
